'use client';
import Image from 'next/image';
import Link from 'next/link';
import React from 'react';

const GeneratedImagesPage = () => {
  const handleDownload = (imageSrc) => {
    const link = document.createElement('a');
    link.href = imageSrc;
    link.download = imageSrc.substring(imageSrc.lastIndexOf('/') + 1);
    link.click();
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-900 to-gray-800 text-white flex flex-col items-center py-10">
      <div className='absolute top-10 left-10'>
        <Link  href="/dashboard"  className="px-6 py-3 rounded-lg bg-gradient-to-r from-purple-600 to-blue-500 text-white font-semibold shadow-lg hover:from-purple-700 hover:to-blue-600 transition-all duration-300">
          ←
          </Link></div>
      <header className="text-center mb-10">
      
        <h1 className="text-5xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-500">
          Generated Images
        </h1>
        <p className="text-gray-400 mt-4">Explore the AI-generated images created just for you.</p>
      </header>


      <main className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 px-5 max-w-7xl">
        {/* Example Image Cards */}
        {[...Array(11)].map((_, index) => {
          const imageSrc = `/examples/garment${index + 1}.png`;
          return (
            <div
              key={index}
              className="bg-gray-800 rounded-lg shadow-lg overflow-hidden hover:shadow-xl transition duration-300"
            >
              <Image
                src={imageSrc}
                alt={`Generated Image ${index + 1}`}
                width={400}
                height={400}
                className="w-full h-56 object-cover"
              />
              <div className="p-4">
                <h3 className="text-lg font-bold">Image {index + 1}</h3>
                <p className="text-gray-400 text-sm mt-2">Generated by AI at 1080p resolution</p>
                <button
                  className="mt-4 w-full py-2 bg-blue-500 hover:bg-blue-600 text-white rounded-lg transition"
                  onClick={() => handleDownload(imageSrc)}
                >
                  Download
                </button>
              </div>
            </div>
          );
        })}
      </main>

      <footer className="mt-16 text-center text-gray-500">
        <p>&copy; 2024 Glamorize AI - All Rights Reserved.</p>
      </footer>
    </div>
  );
};

export default GeneratedImagesPage;
